language: ruby
rvm:
  - 2.2.0
deploy:
  provider: heroku
  app: imei-scraper
  api_key:
    secure: Z3rlHew8Q4vHIz3RcyQz18mgpeOwM3s2PGNS11IAKw63MQiwGN3Vbt84YIqMTeSneQI1ANPb3R76aFibvv4CB0xJTUnNWjmvkAbj6sQ69rNcs2cLoNbXZRrnndrPa1ik9DzY9/RwelMshXGeHuwN4fzgExvMffojITfQflySxZFCElivT7xyNvSyTk1rZJPUNcQoX8Mi39LLaquYLIkVehP0kjLVlJIUB+ZM+AH8FZ99lvRXgszsef1760KfTDEs3lGhZcApdB/FI4iLb/d1oNUWXBEobl86o6ccE6pkiksJp81qtYgxACrWClDE0LlZDcoIRrapNL1f2uo5zA6AaD8a1EgtSYhs9purJgdcFcmmzhUHL5z+93aW8XvcvXEPtyQArBPZy4omJ/Ku8NColgePdFehiwH+vZYy8sl5QiFUcv1AHWf9tERZliRlUyK/3sUz389nxkMn9dwFPyBVlui9whFvGz+nWq1QdgbgxtcjlwtLCzwrJEns+EBXY0h21Y52xJAC5nUWFt80KYppYPwTApBxcp1PExMjVur9baJgpOnJ2akfC+74QqyrTDFwJsHWrAZj3/7Jc00h+pbbISPcfrReRQ3MA2x0735ez3atQaA4QD1eAr9SDKCypT5EKq8GoSGZaXNT/NpDee5ZVQncU/TabSw8sfoLkCYFLV4=
